server:
  port: 8080  # This sets the application to run on port 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # URL for H2 in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Enable the H2 console at runtime

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    show-sql: true  # Show SQL queries in the logs
